### ISSUE TITLE
 Problems-Alternative-Solutions(PAS)

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#18]
Each teammate has to write 2 PAS from each assigned feature:
- [x] @ddummann / Scan
- [x] @Lina-go  / Map
- [x] @eduardoh27 / Recycle information
- [x] @marilynjov / Streak
- [x] @mestradag / My info
- [x] @dcuevasa  / Scoreboard

**Comment by marilynjov** [comment]
PAS were completed referencing each of the features and their effect.
