### ISSUE TITLE
Business Questions

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#20]
10 business questions are divided by type as follows:

- [x] @mestradag , @dcuevasa y @ddummann 

* Type 1: 1 question (App’s telemetry)
* Type 2: 4 questions (Direct user experience improvement)

- [x] @Lina-go , @marilynjov y @eduardoh27 

* Type 3: 3 questions (New or deprecated/updated features)
* Type 4: 1 question (Benefits from data)
* Type 5: 1 question (Combination of two or more types)

**Comment by ddummann** [comment]
this activity helped the project to identify what is important to metric to improve the business.

**Comment by dcuevasa** [comment]
We had some issues with the question types.
