### ISSUE TITLE
Functional Scenarios

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#31]
Provide *12* functional scenarios for your solution. These scenarios are described using the book’s framework (user action, system response and execution context).

**Tasks:**
Each team member writes 2 FS
- [x] @ddummann 
- [x] @Lina-go 
- [x] @eduardoh27 
- [x] @marilynjov 
- [x] @mestradag 
- [x] @dcuevasa

**Comment by mestradag** [comment]
Wrote the functional scenarios about the scanning and maps features.
