### ISSUE TITLE
Quality Scenarios

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#32]
These scenarios are described with the book’s framework in mind (scenario name, quality attributes, app status and context, changes in the context and system reaction). 

**Tasks:**
Each team member writes 2 QS
- [x] @ddummann 
- [x] @Lina-go 
- [x] @eduardoh27 
- [x] @marilynjov 
- [x] @mestradag 
- [x] @dcuevasa

**Comment by mestradag** [comment]
Wrote the Quality scenarios when the app is used in a crowded area during peak hours and While using the SustainU app inside a multi-floor university building where signals are weak
