### ISSUE TITLE
Business questions (BQs)

### ISSUE THREAD

**Issue by Lina-go** [ISIS3510-Team14/Wiki#47]
List all the business questions that you will implement, in this sprint, with their respective type (and rationale if necessary). The  implemented  BQ  should  be part  of the  listyou  madefor  theSprint  1 deliverable.(This is evaluated in the Wiki). Remember it is mandatory that the BQs must be implemented in the analytics system

**Comment by dcuevasa** [comment]
The BQs were added to the wiki
