### ISSUE TITLE
Architectural  design  (AD)

### ISSUE THREAD

**Issue by Lina-go** [ISIS3510-Team14/Wiki#49]
We will provide a complete architecture design that shows us the Architecture design, architecture, and design patterns and tactics that we are going to use. To show these architecture design choices we'll use as many diagrams as needed. A diagram without rationale will not be valid.

General Architecture:
- [x] @ddummann, @Lina-go, @eduardoh27, @marilynjov, @mestradag, @dcuevasa 

Language Architectures:
- [x]  Swift Architecture - @ddummann, @Lina-go, @eduardoh27 
- [x]  Flutter Architecture - @marilynjov, @mestradag, @dcuevasa

**Comment by dcuevasa** [comment]
The general architecture was chosen.
Each team developed the appropiate architecture for ther OS and programming language
