### ISSUE TITLE
Journey map

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#5]
- [x] Green Campus
- [x] Exchange Bliss

**Comment by ddummann** [comment]
[ ] Green Campus
[ ] Exchange Bliss

**Comment by ddummann** [comment]
[ ] Green Campus
[ ] Exchange Bliss

**Comment by ddummann** [comment]
- [x] Green Campus
- [ ] Exchange Bliss

**Comment by eduardoh27** [comment]
done
