### ISSUE TITLE
Ethics Video

### ISSUE THREAD

**Issue by mestradag** [ISIS3510-Team14/Wiki#51]
At the end of each sprint, each team should deliver a video, no longer than 6 mins, in which each member makes a reflection concerning (i) the ethical implications of her work as part of the team, (ii) the societal and environmental impact of the proposed product, (iii) ethical implications of the product.

- [x] @mestradag 
- [x] @Lina-go 
- [x] @eduardoh27 
- [x] @marilynjov 
- [x] @ddummann 
- [x] @dcuevasa

**Comment by dcuevasa** [comment]
everybody recorded their personal videos and they where stitched together and added to the wiki
