### ISSUE TITLE
Evaluate the performance using the profiling too

### ISSUE THREAD

**Issue by dcuevasa** [ISIS3510-Team14/Wiki#63]
Design, implement and justify micro-optimization strategies within the app.For this you have tofirst evaluate the performance using the profiling tool before  the  micro-optimization  implementation,  then  implement  the  optimization, finally use the profiling tool again to test the modified feature.

- [x] Swift @ddummann @Lina-go @eduardoh27 
- [x] Flutter @marilynjov @mestradag @dcuevasa

**Comment by mestradag** [comment]
Fulfill all the requirements
